import path from "path";

/**
 * A constant string representing the callout identifier for the Bible Meditation Helper plugin.
 * This callout is used to mark citations within the plugin.
 */
const pluginCallout = "[!bible-meditation-helper-citation]";
const defaultFolderInVault = "Bible-Meditation-Helper";
const defaultCitationFolder = path.join(defaultFolderInVault, `citations`);

export const mapBibleBookAbbrevToBibleBooks = new Map<string, string>([
    ["gen", "Genesis"],
    ["ex", "Exodus"],
    ["lev", "Leviticus"],
    ["num", "Numbers"],
    ["deut", "Deuteronomy"],
    ["josh", "Joshua"],
    ["judg", "Judges"],
    ["ruth", "Ruth"],

    ["1sam", "I_Samuel"],
    ["isam", "I_Samuel"],
    ["2sam", "II_Samuel"],
    ["iisam", "II_Samuel"],
    ["1kgs", "I_Kings"],
    ["ikgs", "I_Kings"],
    ["2kgs", "II_Kings"],
    ["iikgs", "II_Kings"],
    ["1chr", "I_Chronicles"],
    ["ichr", "I_Chronicles"],
    ["2chr", "II_Chronicles"],
    ["iichr", "II_Chronicles"],

    ["ezra", "Ezra"],
    ["neh", "Nehemiah"],
    ["esth", "Esther"],
    ["job", "Job"],
    ["ps", "Psalms"],
    ["prov", "Proverbs"],
    ["eccl", "Ecclesiastes"],
    ["song", "Song_of_Solomon"],
    ["isa", "Isaiah"],
    ["jer", "Jeremiah"],
    ["lam", "Lamentations"],
    ["ezek", "Ezekiel"],
    ["dan", "Daniel"],
    ["hos", "Hosea"],
    ["joel", "Joel"],
    ["amos", "Amos"],
    ["obad", "Obadiah"],
    ["jonah", "Jonah"],
    ["mic", "Micah"],
    ["nah", "Nahum"],
    ["hab", "Habakkuk"],
    ["zeph", "Zephaniah"],
    ["hag", "Haggai"],
    ["zech", "Zechariah"],
    ["mal", "Malachi"],
    ["matt", "Matthew"],
    ["mark", "Mark"],
    ["luke", "Luke"],
    ["john", "John"],
    ["acts", "Acts"],
    ["rom", "Romans"],

    ["1cor", "I_Corinthians"],
    ["icor", "I_Corinthians"],
    ["2cor", "II_Corinthians"],
    ["iicor", "II_Corinthians"],

    ["gal", "Galatians"],
    ["eph", "Ephesians"],
    ["phil", "Philippians"],
    ["col", "Colossians"],

    ["1thess", "I_Thessalonians"],
    ["ithess", "I_Thessalonians"],
    ["2thess", "II_Thessalonians"],
    ["iithess", "II_Thessalonians"],
    ["1tim", "I_Timothy"],
    ["itim", "I_Timothy"],
    ["2tim", "II_Timothy"],
    ["iitim", "II_Timothy"],

    ["titus", "Titus"],
    ["phlm", "Philemon"],
    ["heb", "Hebrews"],
    ["jas", "James"],

    ["1pet", "I_Peter"],
    ["ipet", "I_Peter"],
    ["2pet", "II_Peter"],
    ["iipet", "II_Peter"],
    ["1john", "I_John"],
    ["ijohn", "I_John"],
    ["2john", "II_John"],
    ["iijohn", "II_John"],
    ["3john", "III_John"],
    ["iiijohn", "III_John"],

    ["jude", "Jude"],
    ["rev", "Revelation_of_John"],

    ["genèse", "Genesis"],
    ["exode", "Exodus"],
    ["lévitique", "Leviticus"],
    ["nombres", "Numbers"],
    ["deutéronome", "Deuteronomy"],
    ["josué", "Joshua"],
    ["juges", "Judges"],
    ["1samuel", "I_Samuel"],
    ["isamuel", "I_Samuel"],

    ["2samuel", "II_Samuel"],
    ["iisamuel", "II_Samuel"],

    ["1rois", "I_Kings"],
    ["irois", "I_Kings"],
    ["2rois", "II_Kings"],
    ["iirois", "II_Kings"],

    ["1chroniques", "I_Chronicles"],
    ["ichroniques", "I_Chronicles"],
    ["2chroniques", "II_Chronicles"],
    ["iichroniques", "II_Chronicles"],

    ["esdras", "Ezra"],
    ["néhémie", "Nehemiah"],
    ["esther", "Esther"],
    ["psaumes", "Psalms"],
    ["proverbes", "Proverbs"],
    ["ecclésiaste", "Ecclesiastes"],
    ["cantique", "Song_of_Solomon"],
    ["ésaïe", "Isaiah"],
    ["jérémie", "Jeremiah"],
    ["lamentations", "Lamentations"],
    ["ézéchiel", "Ezekiel"],
    ["daniel", "Daniel"],
    ["osée", "Hosea"],
    ["joël", "Joel"],
    ["abdias", "Obadiah"],
    ["jonas", "Jonah"],
    ["michée", "Micah"],
    ["nahum", "Nahum"],
    ["habacuc", "Habakkuk"],
    ["sophonie", "Zephaniah"],
    ["aggée", "Haggai"],
    ["zacharie", "Zechariah"],
    ["malachie", "Malachi"],
    ["matthieu", "Matthew"],
    ["marc", "Mark"],
    ["luc", "Luke"],
    ["jean", "John"],
    ["actes", "Acts"],
    ["romains", "Romans"],

    ["1corinthiens", "I_Corinthians"],
    ["icorinthiens", "I_Corinthians"],
    ["2corinthiens", "II_Corinthians"],
    ["iicorinthiens", "II_Corinthians"],

    ["galates", "Galatians"],
    ["éphésiens", "Ephesians"],
    ["philippiens", "Philippians"],
    ["colossiens", "Colossians"],

    ["1thessaloniciens", "I_Thessalonians"],
    ["ithessaloniciens", "I_Thessalonians"],
    ["2thessaloniciens", "II_Thessalonians"],
    ["iithessaloniciens", "II_Thessalonians"],
    ["1timothée", "I_Timothy"],
    ["itimothée", "I_Timothy"],
    ["2timothée", "II_Timothy"],
    ["iitimothée", "II_Timothy"],

    ["tite", "Titus"],
    ["philémon", "Philemon"],
    ["hébreux", "Hebrews"],
    ["jacques", "James"],

    ["1pierre", "I_Peter"],
    ["ipierre", "I_Peter"],
    ["2pierre", "II_Peter"],
    ["iipierre", "II_Peter"],
    ["1jean", "I_John"],
    ["ijean", "I_John"],
    ["2jean", "II_John"],
    ["iijean", "II_John"],
    ["3jean", "III_John"],
    ["iiijean", "III_John"],

    ["apocalypse", "Revelation_of_John"],

    ["genesis", "Genesis"],
    ["exodus", "Exodus"],
    ["leviticus", "Leviticus"],
    ["numbers", "Numbers"],
    ["deuteronomy", "Deuteronomy"],
    ["joshua", "Joshua"],
    ["judges", "Judges"],
    //["ruth", "Ruth"],
    //["1samuel", "I_Samuel"],
    //["2samuel", "II_Samuel"],

    ["1kings", "I_Kings"],
    ["ikings", "I_Kings"],
    ["2kings", "II_Kings"],
    ["iikings", "II_Kings"],
    ["1chronicles", "I_Chronicles"],
    ["ichronicles", "I_Chronicles"],
    ["2chronicles", "II_Chronicles"],
    ["iichronicles", "II_Chronicles"],

    //["ezra", "Ezra"],
    ["nehemiah", "Nehemiah"],
    //["esther", "Esther"],
    //["job", "Job"],
    ["psalms", "Psalms"],
    ["proverbs", "Proverbs"],
    ["ecclesiastes", "Ecclesiastes"],
    ["songofsolomon", "Song_of_Solomon"],
    ["isaiah", "Isaiah"],
    ["jeremiah", "Jeremiah"],
    //["lamentations", "Lamentations"],
    ["ezekiel", "Ezekiel"],
    //["daniel", "Daniel"],
    ["hosea", "Hosea"],
    //["joel", "Joel"],
    //["amos", "Amos"],
    ["obadiah", "Obadiah"],
    //["jonah", "Jonah"],
    ["micah", "Micah"],
    //["nahum", "Nahum"],
    ["habakkuk", "Habakkuk"],
    ["zephaniah", "Zephaniah"],
    ["haggai", "Haggai"],
    ["zechariah", "Zechariah"],
    ["malachi", "Malachi"],
    ["matthew", "Matthew"],
    //["mark", "Mark"],
    //["luke", "Luke"],
    //["john", "John"],
    //["acts", "Acts"],
    ["romans", "Romans"],

    ["1corinthians", "I_Corinthians"],
    ["icorinthians", "I_Corinthians"],
    ["2corinthians", "II_Corinthians"],
    ["iicorinthians", "II_Corinthians"],

    ["galatians", "Galatians"],
    ["ephesians", "Ephesians"],
    ["philippians", "Philippians"],
    ["colossians", "Colossians"],

    ["1thessalonians", "I_Thessalonians"],
    ["ithessalonians", "I_Thessalonians"],
    ["2thessalonians", "II_Thessalonians"],
    ["iithessalonians", "II_Thessalonians"],
    ["1timothy", "I_Timothy"],
    ["itimothy", "I_Timothy"],
    ["2timothy", "II_Timothy"],
    ["iitimothy", "II_Timothy"],

    //["titus", "Titus"],
    ["philemon", "Philemon"],
    ["hebrews", "Hebrews"],
    ["james", "James"],

    ["1peter", "I_Peter"],
    ["ipeter", "I_Peter"],
    ["2peter", "II_Peter"],
    ["iipeter", "II_Peter"],

    ["revelation", "Revelation_of_John"]
]);


export const mapBibleVersionToLanguage = new Map<string, string>([
    ["ESV", "en"],
    ["NIV", "en"],
    ["KJV", "en"],
    ["NLT", "en"],
    ["NRSV", "en"],
    ["RSV", "en"],
    ["NASB", "en"],
    ["ASV", "en"],
    ["WEB", "en"],
    ["BBE", "en"],
    ["DARBY", "en"],
    ["HNV", "en"],
    ["WBT", "en"],
    ["WNT", "en"],
    ["YLT", "en"],
    ["RVR1960", "es"],
    ["LBLA", "es"],
    ["NVI", "es"],
    ["RVR1977", "es"],
    ["RVR1995", "es"],
    ["TLA", "es"],
    //["NVI-PT", "pt"],
    ["ARC", "pt"],
    ["ARA", "pt"],
    ["NVI-PT", "pt"],
    ["LSG", "fr"],
    ["LSG10", "fr"],
    ["NEG", "fr"],
    ["PDV", "fr"],
    ["BDS", "fr"]
]);


export const mapBibleBookToNumericalOrder = new Map<string, number>([
    ["Genesis", 0],
    ["Exodus", 1],
    ["Leviticus", 2],
    ["Numbers", 3],
    ["Deuteronomy", 4],
    ["Joshua", 5],
    ["Judges", 6],
    ["Ruth", 7],
    ["I_Samuel", 8],
    ["II_Samuel", 9],
    ["I_Kings", 10],
    ["II_Kings", 11],
    ["I_Chronicles", 12],
    ["II_Chronicles", 13],
    ["Ezra", 14],
    ["Nehemiah", 15],
    ["Esther", 16],
    ["Job", 17],
    ["Psalms", 18],
    ["Proverbs", 19],
    ["Ecclesiastes", 20],
    ["Song_of_Solomon", 21],
    ["Isaiah", 22],
    ["Jeremiah", 23],
    ["Lamentations", 24],
    ["Ezekiel", 25],
    ["Daniel", 26],
    ["Hosea", 27],
    ["Joel", 28],
    ["Amos", 29],
    ["Obadiah", 30],
    ["Jonah", 31],
    ["Micah", 32],
    ["Nahum", 33],
    ["Habakkuk", 34],
    ["Zephaniah", 35],
    ["Haggai", 36],
    ["Zechariah", 37],
    ["Malachi", 38],
    ["Matthew", 39],
    ["Mark", 40],
    ["Luke", 41],
    ["John", 42],
    ["Acts", 43],
    ["Romans", 44],
    ["I_Corinthians", 45],
    ["II_Corinthians", 46],
    ["Galatians", 47],
    ["Ephesians", 48],
    ["Philippians", 49],
    ["Colossians", 50],
    ["I_Thessalonians", 51],
    ["II_Thessalonians", 52],
    ["I_Timothy", 53],
    ["II_Timothy", 54],
    ["Titus", 55],
    ["Philemon", 56],
    ["Hebrews", 57],
    ["James", 58],
    ["I_Peter", 59],
    ["II_Peter", 60],
    ["I_John", 61],
    ["II_John", 62],
    ["III_John", 63],
    ["Jude", 64],
    ["Revelation_of_John", 65]
]);


    export { pluginCallout, defaultCitationFolder, defaultFolderInVault };